[package]
# Manganese is a rusting catalyst. Manganis makes it faster to collect rust assets (and has almost no google search results)
name = "manganis"
version = "0.1.1"
authors = ["Evan Almloff"]
edition = "2021"
description = "Ergonomic, Automatic, cross crate asset collection"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["assets"]

[lib]

[dependencies]
manganis-macro = { path = "./macro", version = "0.1.1" }
dioxus-core = { git = "https://github.com/DioxusLabs/dioxus", optional = true }

[workspace]
members = ["macro", "common", "cli-support", "test-package", "test-package/test-package-dependency", "test-package/test-package-nested-dependency"]

[features]
default = ["dioxus"]
html = []
dioxus = ["dioxus-core"]
