[package]
# Manganese is a rusting catalyst. Manganis makes it faster to collect rust assets (and has almost no google search results)
name = "manganis"
version = "0.2.2"
authors = ["Evan Almloff"]
edition = "2021"
description = "Ergonomic, automatic, cross crate asset collection and optimization"
license = "MIT OR Apache-2.0"
repository = "https://github.com/DioxusLabs/dioxus/"
homepage = "https://dioxuslabs.com"
keywords = ["assets"]

[lib]

[dependencies]
manganis-macro = { path = "./macro", version = "0.2.1" }
dioxus-core = { version = "0.5.0-alpha.0", optional = true }

[workspace]
members = ["macro", "common", "cli-support", "test-package", "test-package/test-package-dependency", "test-package/test-package-nested-dependency"]

[features]
default = ["dioxus"]
html = []
dioxus = ["dioxus-core"]
url-encoding = ["manganis-macro/url-encoding"]
