[package]
name = "assets-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.183", features = ["derive"] }
toml = "0.7.6"
cargo-lock = { version = "9.0.0", features = ["dependency-tree"] }
project-root = "0.2.2"
cargo_toml = "0.15.3"
petgraph = "0.6.3"
uuid = { version = "1.4.1", features = ["v4", "fast-rng","macro-diagnostics"] }

# Tailwind
railwind = "0.1.5"

# Font conversion
ttf-parser = "0.19.1"

# Image compression/conversion
# JPEG
mozjpeg = "0.9.6"
# PNG
imagequant = "4.2.0"
png = "0.17.9"
# GIF
gifski = "1.12.0"
# Conversion
image = "0.24.7"

# CSS Minification
lightningcss = "1.0.0-alpha.44"