[package]
name = "manganis-cli-support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manganis-common = { path = "../common" }

serde = { version = "1.0.183", features = ["derive"] }
toml = "0.7.6"
cargo-lock = { version = "9.0.0", features = ["dependency-tree"] }
cargo_metadata = "0.17.0"
cargo_toml = "0.15.3"
petgraph = "0.6.3"
anyhow = "1"
rayon = "1.7.0"

# Tailwind
railwind = "0.1.5"

# Image compression/conversion
# JPEG
mozjpeg = "0.9.6"
# PNG
imagequant = "4.2.0"
png = "0.17.9"
# Conversion
image = { version = "0.24.7" }

# CSS Minification
lightningcss = "1.0.0-alpha.44"

# Remote assets
url = { version = "2.4.0", features = ["serde"] }
reqwest = { version = "0.11.18", features = ["blocking"] }
log = "0.4.20"

[features]
default = []
avif = ["image/avif-encoder"]
webp = ["image/webp-encoder"]
html = ["manganis-common/html"]
