[package]
name = "assets-cli-support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assets-common = { path = "../common" }

serde = { version = "1.0.183", features = ["derive"] }
toml = "0.7.6"
cargo-lock = { version = "9.0.0", features = ["dependency-tree"] }
cargo_metadata = "0.17.0"
project-root = "0.2.2"
cargo_toml = "0.15.3"
petgraph = "0.6.3"
uuid = { version = "1.4.1", features = ["v4", "fast-rng","macro-diagnostics"] }
anyhow = "1"
rayon = "1.7.0"

# Tailwind
railwind = "0.1.5"

# Image compression/conversion
# JPEG
mozjpeg = "0.9.6"
# PNG
imagequant = "4.2.0"
png = "0.17.9"
# Conversion
image = { version = "0.24.7", features = ["avif-encoder", "webp-encoder"] }

# CSS Minification
lightningcss = "1.0.0-alpha.44"

# Remote assets
url = { version = "2.4.0", features = ["serde"] }
reqwest = { version = "0.11.18", features = ["blocking"] }

[patch.crates-io]
built = { git = "https://github.com/lukaslueg/built" }
