name: macOS tests

on:
  push:
    branches:
      - main
    paths:
      - cli-support/src/**
      - cli-support/examples/**
      - cli-support/Cargo.toml
      - common/src/**
      - common/examples/**
      - common/Cargo.toml
      - macro/src/**
      - macro/examples/**
      - macro/Cargo.toml
      - examples/**
      - src/**
      - .github/**
      - Cargo.toml

  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - cli-support/src/**
      - cli-support/examples/**
      - cli-support/Cargo.toml
      - common/src/**
      - common/examples/**
      - common/Cargo.toml
      - macro/src/**
      - macro/examples/**
      - macro/Cargo.toml
      - examples/**
      - src/**
      - .github/**
      - Cargo.toml

jobs:
  test:
    if: github.event.pull_request.draft == false
    name: Test Suite
    runs-on: macos-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v4
      - run: cargo test --all --tests
